export default {
  userLogin: 'user/login',
  userRegister: 'user/registration',
  getCategory: 'category-data',
  getCoupon: 'coupon-data',
  getUser: 'user-data',
  redeem: 'redeem',
  getRedeem:'redeem-data',
  getCategoryCoupon:'getCouponbyCategoryId',
  userLogout:'logout',
  getBanner:'getBannerImage',
  updateLocation:'updateUserLocation',
  redeemCouponbyUser:'redeemedCouponbyUser',
  getNotification:'notification',
};
